name: CorpX Workflow

run-name: CorpX Workflow

on:
    # Trigger Events
    push:
        branches:
            -main
        paths-ignore:
            - ".gitignore"
            - "README.md"
            - "CONTRIBUTING.md"
            - "LICENSE.txt"

    pull_request:
        branches:
            - main
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
jobs:
    test:
        #TODO: Setup Node + Dependencies
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4
        - name: Use Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '18.x'
        - name: install dependencies
          run: npm ci

        #TODO: Run all the Linters
        - name: run linters
          run: npm run lint:all

        #TODO: Run all scripts in folder script/**
        - name: run scripts
          run: node script/url-checker.js -t $URL_CHECKER_TIMEOUT -d src/posts
          env: 
            URL_CHECKER_TIMEOUT: ${{ vars.URL_CHECKER_TIMEOUT }}
        #TODO: Implement URL_CHECKER_TIMEOUT variable

    build:
        runs-on: ubuntu-latest
        steps:
        #TODO: Check that test job succeeded
        #Setup Node
        - uses: actions/checkout@v4
        - name: Use Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '18.x'
        - name: install dependencies
          run: npm ci
        #Setup Pages
        - name: setup pages
          uses: actions/configure-pages@v4
        #Build Pages with Elevendy
        - name: Build Static Pages
          run: node eleventy:prod
          env: 
            PATH_PREFIX: ${{ vars.PATH_PREFIX }}
        #Upload content of _site as an artifact
        - name: download _site artifact
          uses: actions/download-artifact@v4
          with:
            name: site_artifact
            path: _site
            
    #deploy: #TODO: Deploy Job

    #TODO: Force Deployment Option

    #TODO: Limit of 1 Runs

    

    

    
